### ISSUE TITLE
msa is allowed to use an amino acid substitution matrix even though type='dna'

### ISSUE THREAD

**Issue by francoiskroll** [UBod/msa#13]
For example, `msa(c('ACGT', 'ACCT'), type='dna', method='ClustalOmega')`

uses the gonnet substitution matrix!

I am not sure this should be default behaviour? I have been aligning DNA sequences with an amino acid substitution matrix for a while, I'm only noticing now!

With `type='dna'` explicitly present, I don't think it should be ok for msa to use an amino acid substitution matrix. Throwing an Error in this case would make more sense to me.

Thanks!

**Comment by UBod** [comment]
The help page of `msaClustalOmega()` states the following: "Since ClustalOmega only allows for using built-in amino acid substitution matrices, it is hardly useful for multiple alignments of nucleotide sequences." It is true that we could have implemented the function so that it does not accept any other sequences than amino acid sequences. We decided in favor of a more open solution - along with the above warning. So the user can still ClustalOmega for DNA and RNA sequences - but at his/her own risk.

**Comment by francoiskroll** [comment]
I did notice that warning at some point but brushed it off as it mentioned _multiple alignments_. I am doing one-to-one so I assumed I was fine!

I'm not sure anyone would ever want to align DNA sequences with an amino acid substitution matrix? But it's your call. Thanks a lot for your reply!
