### ISSUE TITLE
M2 Mac - pretty print error

### ISSUE THREAD

**Issue by SevanEsaian** [UBod/msa#21]
Hello, 
I am trying to go through the msa documentation; however, I am unable to get pretty print to function properly. 
When I run the following command:

```
msaPrettyPrint(myFirstAlignment, y=c(164, 213), output="asis",
               showNames="none", showLogo="none", askForOverwrite=FALSE)
```
R asks me the following question: `File myFirstAlignment.tex exists. Overwrite? (y/N)`
When I type in `y`, it gives me the following error: 
```
Error in texi2dvi(texfile, quiet = !verbose, pdf = identical(output, "pdf"),  : 
  pdflatex is not available
```

I don't know how to solve this issue. I would appreciate your help.

**Comment by UBod** [comment]
The problem lies outside of the 'msa' package: You do not have a TeX/LaTeX system installed. I suppose the easiest solution is to install the 'tinytex' package from CRAN. Please give this a try. If it does not work, please let me know. Maybe I will demand 'tinytex' as dependency in the future, so its installation is enforced.
