### ISSUE TITLE
msaPrettyPrint output to folder

### ISSUE THREAD

**Issue by snutebiller** [UBod/msa#33]
Hello, I print multiple sequence alignments using `msaPrettyPrint` for which I would like to output into a folder. When providing the folder in the `file =` argument, the `.tex` file is indeed created in the specified folder, the `.pdf` however is created in the current working directory. Would it be possible to output the `.pdf` in the specified folder too?

```
library(msa)

set.seed(897)
nuc <- c('A' , 'C', 'T', 'G')
seq <- replicate(10, paste(sample(nuc, 8, replace = TRUE), collapse = ""))
align <- msa(seq, type = 'dna')
msaPrettyPrint(align, file = "test/plot.pdf")
```

**Comment by UBod** [comment]
Thanks for bringing up this issue and for your interest in our package, @snutebiller! I have been aware of this issue for quite some time. It is actually outside of the scope of the `msa package, but it is caused` by the `texi2dvi()` function from the `tools` package. This function does not allow for specifying the output directory, but only the input file. Wherever the input file is located, it outputs all files (`.aux`, `.log` and also the final `.pdf`) into the current working directory (the reason is that so does the `pdflatex` command). So all I can offer is to suggest to change the working directory using `setwd()` before you run `msaPrettyPrint()`.
